default_platform(:android)

platform :android do

  desc "Deploy to Google Play Internal Testing"
  lane :android_internal do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "internal",
      json_key: "google-play.json"
    )
  end

  desc "Deploy to Google Play Production"
  lane :android_production do
    gradle(
      task: "bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      track: "production",
      json_key: "google-play.json"
    )
  end

end
