name: iOS CI & TestFlight

on:
  push:
    branches:
      - dev

jobs:
  ios-testflight:
    name: Build & Upload to TestFlight
    
    uses: ./.github/workflows/ios-common.yml

    with:
      lane: ios_internal
      
    secrets: inherit
