name: iOS CI & TestFlight

on:
  push:
    branches:
      - develop
    paths:
      - 'ios/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/ios-*'
      

jobs:
  ios-testflight:
    name: Build & Upload to TestFlight
    
    uses: ./.github/workflows/ios-common.yml

    with:
      lane: ios_internal
      
    secrets: inherit
