name: iOS Production Deployment

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'ios/**'
      - 'src/**'
      - 'package.json'
      - 'package-lock.json'
      - 'yarn.lock'
      - '.github/workflows/ios-*'

jobs:
  deploy-production:
    if: github.event.pull_request.merged == true &&
        github.event.pull_request.head.ref == 'develop'

    uses: ./.github/workflows/ios-common.yml

    with:
      lane: ios_production

    secrets: inherit
